### PR TITLE
Issue/570 no limit for patient name

### LINKED ISSUE #570: There is no limit for a patient name
### Describe the bug

There is no limit for the patient name when assigned to a bed which creates some visual problems

### Describe how to produce the bug

add as many chars as you want ot the name of a patient when assining to a bed

### Additional context

grafik

### PR DESCRIPTION
**Pull request by florianjs**
## Which issues does this pull request close?
closes #570

## [OPTIONAL] Give testing instructions to reviewers
image

### CODE REVIEW

File: tasks/components/cards/PatientCard.tsx [hunk 1]
```diff
@@ -27,8 +27,8 @@ export const PatientCard = ({
   return (
     <Card isSelected={isSelected} onTileClick={onTileClick}>
       <div className={tw('flex flex-row justify-between')}>
-        <Span type="subsubsectionTitle">{bedName}</Span>
-        <Span>{patientName}</Span>
+        <Span className={tw('whitespace-nowrap')} type="subsubsectionTitle">{bedName}</Span>
+        <span className={tw('ml-2 text-ellipsis overflow-hidden block  whitespace-nowrap')}>{patientName}</span>
```
Comment (DasProffi) [inline tasks/components/cards/PatientCard.tsx:31]: preferably use truncate

**Review by DasProffi — CHANGES_REQUESTED** [review]

File: tasks/components/cards/PatientCard.tsx (hunk 1 above)
Comment (florianjs) [reply tasks/components/cards/PatientCard.tsx:31]: Instead of text-ellipsis?

Comment (DasProffi) [reply tasks/components/cards/PatientCard.tsx:31]: truncate does this in tailwind and doesn't require you to write four key words, and also use our span for easier typography management. The line below does exactly what you want
```suggestion
        <Span className={tw('ml-2 truncate')}>{patientName}</Span>
```

**Review by DasProffi — APPROVED** [review]
