### PR TITLE
fix landing page translations

### LINKED ISSUE #920: Fix translations in header
### Describe the bug

talks is translated with tasks

### Describe how to produce the bug

Use German, and you will see the wrong translation.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #920

### CODE REVIEW

File: landing-page/components/sections/landing/ExpansionSection.tsx [hunk 1]
```diff
@@ -20,7 +20,7 @@ const defaultExpansionTranslation: Record<Languages, ExpansionSectionTranslation
   de: {
     germanyHealthcareSystem: 'Deutsches Gesundheitssystem',
     hospitals: 'Krankenhäuser',
-    healthcareWorkers: 'healthcare workers',
+    healthcareWorkers: 'healthcare Arbeiter',
```
Comment (MaxSchaefer) [inline landing-page/components/sections/landing/ExpansionSection.tsx:23]:
```suggestion
    healthcareWorkers: 'healthcare worker',
```

File: landing-page/pages/index.tsx [hunk 2]
```diff
@@ -11,7 +14,27 @@ import PartnerSection from '../components/sections/landing/Partners'
...
+}
+
+const defaultHomePageTranslation : Record<Languages, HomePageTranslation> = {
+  en: {
+    checkOutFirstProduct: 'Check out our first product',
+    checkOutFirstProductDescription: 'and how helpwave tasks increases productivity for our medical heroes',
+    helpwaveTasks: 'helpwave tasks'
+  },
+  de: {
+    checkOutFirstProduct: 'Sieh unser erstes Produkt an',
```
Comment (MaxSchaefer) [inline landing-page/pages/index.tsx:30]:
```suggestion
    checkOutFirstProduct: 'Sieh dir unser erstes Produkt an',
```

**Review by MaxSchaefer — APPROVED** [review]
