### PR TITLE
fix(web): Add a visual limits to the room name

### LINKED ISSUE #281: Room name should be limited or caped at a certain limit
The name of a room in a Station should be limited or the visualization should be capped at a certain limit.

grafik

### PR DESCRIPTION
**Pull request by Paul-B98**
closes #281 

this will limit the limit the length of the room names that are shown

### CODE REVIEW

**Review by florian-sabonchi — APPROVED** [review]

File: tasks/components/RoomList.tsx [hunk 1]
```diff
@@ -219,6 +222,8 @@ export const RoomList = ({
                           name: text
                         } : value))}
                         id={cell.row.original.name}
+                        maxLength={maxRoomNameLength}
+                        minLength={minRoomNameLength}
```
Comment (MaxSchaefer) [inline tasks/components/RoomList.tsx:226]:
```suggestion
                        minLength={minRoomNameLength}
                        maxLength={maxRoomNameLength}
```
_nit_

File: tasks/components/RoomList.tsx [hunk 2]
```diff
@@ -101,6 +101,9 @@ export const RoomList = ({
   const [stateDeletionConfirmDialog, setDeletionConfirmDialogState] = useState(defaultState)
   const resetDeletionConfirmDialogState = () => setDeletionConfirmDialogState(defaultState)
 
+  const minRoomNameLength = 2
```
Comment (MaxSchaefer) [inline tasks/components/RoomList.tsx:104]:
```suggestion
  const minRoomNameLength = 1
```
https://github.com/helpwave/web/issues/281#issuecomment-1520767575

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]

**Review by MaxSchaefer — APPROVED** [review]

**Comment by Paul-B98** [comment]
@MaxSchaefer can u merge this i don't have the permissions
