### PR TITLE
fix: empty inputs

### LINKED ISSUE #426: empty names
We should check for empty names to avoid erroing occuring through this
image

### PR DESCRIPTION
**Pull request by florian-sabonchi**
closes #426

### CODE REVIEW

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
We should move the trim to the input instead.

**Review by DasProffi — APPROVED** [review]

**Review by MaxSchaefer — COMMENTED** [review]
What's the purpose behind the extra `set[InputAttributeName]` `useState` hook?

**Comment by florian-sabonchi** [comment]
> What's the purpose behind the extra `set[InputAttributeName]` `useState` hook?

Otherwise the user cannot enter spaces, because in onChangeEvengt laws value is passed as value to the input. Thus it would no longer be possible to enter spaces this would be a compromise

**Comment by MaxSchaefer** [comment]
> > What's the purpose behind the extra `set[InputAttributeName]` `useState` hook?
> 
> Otherwise the user cannot enter spaces, because the Value set in the onChangeEvent is is passed as value to the custom input.

Okay, then you can move the `.trim()` logic into the `validate...()` functions. These are called by `triggerOnChange()`.

File: tasks/components/OrganizationForm.tsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ export const OrganizationForm = ({
   const inputClasses = tw('mt-1 block rounded-md w-full border-gray-300 shadow-sm focus:outline-none focus:border-hw-primary-500 focus:ring-hw-primary-500')
 
   function validateShortName(organization: OrganizationGeneralInfoDTO) {
-    if (organization.shortName === '') {
+    if (organization.shortName.trim() === '') {
```
Comment (MaxSchaefer) [inline tasks/components/OrganizationForm.tsx:100]: It would be smart if we move `organization.shortName` into a separate variable. This variable should be then used throughout the rest of the function. This applies for all `validate...()` functions.

**Review by MaxSchaefer — APPROVED** [review]

**Review by MaxSchaefer — APPROVED** [review]
