### PR TITLE
force unchecked state for task template subtasks

### LINKED ISSUE #519: Checkboxes are mutable on task templates
### Describe the bug

The checkboxes for subtasks by editing task templates are mutable.
Obviously, these subtasks will be unchecked when using the template on a real task.
So it makes no differences in weather the subtask is checked or not.

We should make the checkboxes for subtasks unchecked the entire time and disable them, too.

### Describe how to produce the bug

Just edit any task template and add subtasks to it.

### Additional context

#505

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #519

### CODE REVIEW

**Review by use-to — CHANGES_REQUESTED** [review]

**Comment by florianjs** [comment]
We should also consider the case when a new subtask is created, then the ID is also empty and we should check for undefindend.

File: tasks/components/SubtaskView.tsx [hunk 1]
```diff
@@ -100,6 +100,11 @@ export const SubtaskView = ({
                   }
                 }}
                 onDoneChange={done => {
+                  // taskTemplateId === "" for the creation of a template
```
Comment (florianjs) [inline tasks/components/SubtaskView.tsx:103]: if (taskTemplateId || taskTemplateId === '') {
     return
 }

**Review by florianjs — CHANGES_REQUESTED** [review]

File: tasks/components/SubtaskView.tsx [hunk 2]
```diff
@@ -100,6 +100,11 @@ export const SubtaskView = ({
...
+                  if (taskTemplateId) {
```
Comment (florianjs) [inline tasks/components/SubtaskView.tsx:104]:
```suggestion
    if (taskTemplateId || taskTemplateId === '') {
      return
    }
```

**Review by use-to — APPROVED** [review]

File: tasks/components/SubtaskView.tsx (hunk 2 above)
Comment (DasProffi) [reply tasks/components/SubtaskView.tsx:104]: creates are should indicated by an empty string for id and not undefined

Comment (florianjs) [reply tasks/components/SubtaskView.tsx:104]: Yes, but then we still have the problem that the problem occurs when creating the checkbox.

Comment (florianjs) [reply tasks/components/SubtaskView.tsx:104]: > creates should be indicated by an empty string for id and not undefined

Yes, but we should check of !== undefinded because if we have an empty string it's not undefinded
