### PR TITLE
fix: remove rooms without beds from RoomOverview

### LINKED ISSUE #526: Remove room description if no beds have been assigned
### Describe the feature

I suggest removing the name of a room from the room overview if no beds have been assigned.

### Why is this feature needed?

Information that is not required should also not be displayed in my opinion

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by florianjs**
## Which issues does this pull request close?
closes #526

### CODE REVIEW

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
https://github.com/helpwave/web/issues/526#issuecomment-1666182769

File: tasks/components/RoomOverview.tsx [hunk 1]
```diff
@@ -39,10 +39,12 @@ export const RoomOverview = ({ room }: RoomOverviewProps) => {
...
-      <div className={tw('flex flex-row items-center mb-1')}>
-        <div className={tw('w-2 h-2 mx-2 rounded-full bg-gray-300')}/>
-        <Span type="subsectionTitle">{room.name}</Span>
-      </div>
+      { room.beds.length > 0 ? (
+        <div className={tw('flex flex-row items-center mb-1')}>
+          <div className={tw('w-2 h-2 mx-2 rounded-full bg-gray-300')}/>
+          <Span type="subsectionTitle">{room.name}</Span>
+        </div>
+      ) : ''}
```
Comment (DasProffi) [inline tasks/components/RoomOverview.tsx:47]: Don't fix it here but in the `WardRoomList` component

**Review by DasProffi — CHANGES_REQUESTED** [review]

File: tasks/components/layout/WardRoomList.tsx [hunk 2]
```diff
@@ -68,10 +68,12 @@ export const WardRoomList = ({
         hasError={isError}
       >
         {rooms && rooms.map(room => (
+          room.beds.length > 0 ? (
             <RoomOverview
               key={room.id}
               room={room}
             />
+          ) : ''
```
Comment (DasProffi) [inline tasks/components/layout/WardRoomList.tsx:76]: use a filter instead
```suggestion
        {rooms && rooms.filter(room => room.beds.length > 0).map(room => ( 
            <RoomOverview
              key={room.id}
              room={room}
            />
```

**Review by DasProffi — APPROVED** [review]

**Review by DasProffi — APPROVED** [review]

**Review by MaxSchaefer — APPROVED** [review]
