### PR TITLE
update feature display and fix TwoColumn using the wrong width

### LINKED ISSUE #645: Feature list wide layout no padding
### Describe the bug

there is no padding between the title and the picture
image

### Describe how to produce the bug

Change the slider on the index page

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #645

### CODE REVIEW

File: tasks/components/layout/TwoColumn.tsx [hunk 1]
```diff
@@ -141,7 +145,7 @@ export const TwoColumn = ({
             className={tw(`overflow-hidden`)}
             style={{ width: leftWidth + 'px' }}
           >
-            <SimpleBarReact ref={scrollableRefLeft} style={{ overflowX: 'hidden', maxHeight: simpleBarMaxHeight }}>
```
Comment (florianjs) [inline tasks/components/layout/TwoColumn.tsx:144]: why do you removed overflowX: 'hidden'?

Comment (DasProffi) [reply tasks/components/layout/TwoColumn.tsx:144]: Because it causes the width calculation to be off and with the corrected version the width should always match

**Review by use-to — APPROVED** [review]
Finally no more warnings...
