### PR TITLE
make Carousel slide and drag controllable

### LINKED ISSUE #1071: Slider not slidable on mobile
### Describe the bug

Slider not slidable on mobile.

### Describe how to produce the bug

Try to swipe the slider on a mobile device.

### Additional context

Currently only clicks work

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #1071

## [OPTIONAL] Give testing instructions to reviewers
Look at the preview of out landing page on the start screen there is a slider

### CODE REVIEW

File: lib/components/layout/Carousel.tsx [hunk 1]
```diff
@@ -56,112 +69,147 @@ export const Carousel = ({
...
+    offset,
+    dragState,
+    animationState,
+  }, setCarouselInformation] = useState<CarouselInformation>({
+    currentIndex: 0,
+    offset: 0,
   })
-  const animationTime: number = 250 // in ms
+  const isAnimating = animationState !== undefined
+  const cardsPerSecond: number = 4 // in ms per card, musst be != 0
```
Comment (MaxSchaefer) [inline lib/components/layout/Carousel.tsx:82]:
```suggestion
  const cardsPerSecond: number = 4 // in ms per card, must be != 0
```

**Review by MaxSchaefer — APPROVED** [review]

**Review by MaxSchaefer — APPROVED** [review]

**Review by use-to — CHANGES_REQUESTED** [review]
Can we add a slide transition of 5s.
And can we make it repetitive?

**Comment by DasProffi** [comment]
Changes in #1092
