### PR TITLE
fix: typo

### LINKED ISSUE #322: fix typo

### PR DESCRIPTION
**Pull request by florian-sabonchi**
closes #322

### CODE REVIEW

File: tasks/components/OrganizationForm.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const defaultOrganizationFormTranslations: Record<Languages, OrganizationFormTra
     shortNameDescription: 'Häufig verwendet, sollte kurz und beschreibend sein.',
     longName: 'Ausgeschriebener Name',
     longNameDescription: 'Selten verwendet, falls der Platz zur Darstellung reicht.',
-    contactEmail: 'Kontkct email',
+    contactEmail: 'Kontakt email',
```
Comment (MaxSchaefer) [inline tasks/components/OrganizationForm.tsx:47]:
```suggestion
    contactEmail: 'Kontakt E-Mail',
```

**Review by MaxSchaefer — APPROVED** [review]

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
_See previous request_

**Review by MaxSchaefer — APPROVED** [review]
